### ISSUE TITLE
独立进行StrainPanDA测试

### ISSUE THREAD

**Issue by hh1985** [xbiome/StrainPanDA#17]
独立进行StrainPanDA测试，并提出反馈意见。

**Comment by liwenqingi** [comment]
按github说明搭建完环境后，run full analysis报错
executor >  local (5)
[ec/8121df] process > panphlanMap (SRR5813299|Faecalibacterium-prausnitzii-202009) [100%] 4 of 4 ?
[b2/9e1cb3] process > mergeProfile (Faecalibacterium-prausnitzii-202009)           [100%] 1 of 1, failed: 1 ?
[-        ] process > runStrainPanDAR                                              -
[-        ] process > runMinPath                                                   -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'mergeProfile (Faecalibacterium-prausnitzii-202009)'

Caused by:
  Process `mergeProfile (Faecalibacterium-prausnitzii-202009)` terminated with an error exit status (1)

Command executed:

  merge_tables.r -p "*bz2" -o Faecalibacterium-prausnitzii-202009.counts.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error in library(getopt) : 不存在叫‘getopt’这个名字的程辑包
  停止执行

Work dir:
  /share/home/liwenqing/liwenqing_hpc/6_work_2022/1_strainpanda_test/work/b2/9e1cb37dec159cf8d44a47d6496e29

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
